# Generated by Django 4.1 on 2023-12-27 05:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0003_product_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.ImageField(
                blank=True, default="/sample.jpg", null=True, upload_to=""
            ),
        ),
    ]
